### ISSUE TITLE
Clarify "work" for file IMG_3211.xml

### ISSUE THREAD

**Issue by sterkenburgsara** [HeardLibrary/exhibitions#45]
I am confused about the file "IMG_3211.xml" - what is the work? Are we taking digital image of the model, which is the work? It looks like, instead, you're considering the digital image as the work (since its agent is Ed Warga) - but then we can't also have an image record of the image. I'm not sure, but this example may 'break' VRA schema (kudos if it does?? ha!). But on the meta level, I'm confused about this one...curious to get your opinion/thoughts?

**Comment by CliffordAnderson** [comment]
I'd say the work is the born digital photographic image, presumably the archival format–a RAW or TIFF file. The image is a derived version of the original work. I agree that born digital materials do not fit well with the VRA approach. But I'd be hesitant to designate the scene as a work since it's ephemeral and transitory without its representation. But I'll follow your advice if you'd like me to update the description.

**Comment by sterkenburgsara** [comment]
Okay, that description is helpful. It definitely doesn't work easily into the VRA schema, but I think it can work. Close #45.
